DROP TABLE IF EXISTS SMART_READ;

CREATE TABLE SMART_READ (
    ACCOUNT_NUMBER IDENTITY PRIMARY KEY NOT NULL,
    GAS_ID LONG NOT NULL,
    ELEC_ID LONG NOT NULL,
    ELEC_SMART_READ DOUBLE NOT NULL,
    GAS_SMART_READ DOUBLE NOT NULL
);

INSERT INTO SMART_READ(GAS_ID, ELEC_ID, ELEC_SMART_READ, GAS_SMART_READ) VALUES (1, 1, 200.0, 350.5);