DROP TABLE IF EXISTS SMART_READ;

CREATE TABLE SMART_READ (
    ACCOUNT_NUMBER IDENTITY PRIMARY KEY NOT NULL,
    GAS_ID LONG NOT NULL,
    ELEC_ID LONG NOT NULL,
    ELEC_SMART_READ DOUBLE NOT NULL,
    GAS_SMART_READ DOUBLE NOT NULL
);

INSERT INTO SMART_READ(GAS_ID, ELEC_ID, ELEC_SMART_READ, GAS_SMART_READ) VALUES (1, 1, 200.0, 350.5);
INSERT INTO SMART_READ(GAS_ID, ELEC_ID, ELEC_SMART_READ, GAS_SMART_READ) VALUES (2, 2, 275.0, 1203.2);
INSERT INTO SMART_READ(GAS_ID, ELEC_ID, ELEC_SMART_READ, GAS_SMART_READ) VALUES (3, 3, 542.0, 32.9);
INSERT INTO SMART_READ(GAS_ID, ELEC_ID, ELEC_SMART_READ, GAS_SMART_READ) VALUES (4, 4, 102.0, 445.0);
INSERT INTO SMART_READ(GAS_ID, ELEC_ID, ELEC_SMART_READ, GAS_SMART_READ) VALUES (5, 5, 40.3, 30.6);
INSERT INTO SMART_READ(GAS_ID, ELEC_ID, ELEC_SMART_READ, GAS_SMART_READ) VALUES (6, 6, 2450.3, 8250.5);
INSERT INTO SMART_READ(GAS_ID, ELEC_ID, ELEC_SMART_READ, GAS_SMART_READ) VALUES (7, 7, 242.0, 621.1);