DROP TABLE IF EXISTS SMART_READ;

CREATE TABLE SMART_READ (
    ACCOUNT_NUMBER IDENTITY PRIMARY KEY NOT NULL,
    GAS_ID LONG NOT NULL,
    ELEC_ID LONG NOT NULL,
    ELECT_SMART_READ DOUBLE NOT NULL,
    GAS_SMART_READ DOUBLE NOT NULL
);